#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
Unified figure style for sanger.

Centralises the Sanger channel palette and matplotlib rcParams so every figure
generated by the package (the CLI, the report, the README examples) looks
consistent: dye-channel colours, axis cosmetics, figure size/DPI.

The base-to-colour mapping matches the classic Sanger viewer convention used in
the original ``plot.png`` demo: G=black, A=green, C=blue, T=red.
"""

from __future__ import annotations

#: canonical dye-channel colour per base
BASE_TO_COLOR = {"A": "g", "C": "b", "G": "k", "T": "r", "N": "0.6"}

#: default legend label order
BASE_ORDER = ["A", "C", "G", "T"]

#: default figure size (inches) for a chromatogram
FIGURE_WIDTH = 16.0
FIGURE_HEIGHT = 5.0
DPI = 150


def apply(dpi: int = DPI) -> None:
    """Apply the canonical Sanger figure theme to matplotlib's rcParams."""
    from ._mpl import require_matplotlib

    require_matplotlib()
    import matplotlib as mpl

    mpl.rcParams.update(
        {
            "figure.dpi": dpi,
            "savefig.dpi": dpi,
            "savefig.bbox": "tight",
            # minimal, publication-style framing
            "axes.edgecolor": "0.4",
            "axes.linewidth": 0.8,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": False,
            "legend.frameon": False,
            "legend.fontsize": "medium",
            "font.size": 10,
            "xtick.color": "0.3",
            "ytick.color": "0.3",
        }
    )


def channel_colors(base_order=None):
    """Return an ordered ``(base, color)`` list for a given base order."""
    order = base_order or BASE_ORDER
    return [(b, BASE_TO_COLOR.get(b, "0.5")) for b in order]


__all__ = [
    "apply",
    "BASE_TO_COLOR",
    "BASE_ORDER",
    "channel_colors",
    "FIGURE_WIDTH",
    "FIGURE_HEIGHT",
    "DPI",
]
